### ISSUE TITLE
Missing configs in scripts/mopo folder

### ISSUE THREAD

**Issue by XingshuaiHuang** [guangheli12/DiffStitch#1]
Hi there,

I found your work DiffStitch innovative and I'm trying to reproduce this work. As I proceeded, I found that the configs in scripts/mopo folder were missing, which caused errors in " config_path = f"configs.{task}"" in Line 92 in scripts/mopo/train.py. Could you please help address this issue?

Thanks!

**Comment by guangheli12** [comment]
Hi! Sorry for the late reply. I was too busy with phd admission paper work these days.
I have uploaded the config file in scripts/mopo/config. As we kept this config file the same across all environments, if you want to test it on a new environment, all you have to do is to change the name of the config file but keep all the things inside the same.
Hope you can find this repo usefull!

**Comment by XingshuaiHuang** [comment]
Thanks for the update. It works now and it's helpful.
